# Generated by Django 4.0.5 on 2022-07-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0003_account_name_alter_account_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
